function[T,fval,exitflag]=fSolver_Tot(TempVec_ittm,TempVecB_ittm,Humidity_ittm,MeteoData,...
		Int_ittm,ExWater_ittm,Vwater_ittm,Owater_ittm,SoilPotW_ittm,CiCO2Leaf_ittm,TempDamp_ittm,ViewFactor,...
		Gemeotry_m,ParTree,geometry,FractionsGround,FractionsRoof,...
		WallLayers,ParSoilGround,ParInterceptionTree,...
		PropOpticalGround,PropOpticalWall,PropOpticalTree,...
		ParThermalGround,ParThermalWall,ParVegGround,ParVegTree,...
        ParSoilRoof,PropOpticalRoof,ParThermalRoof,ParVegRoof,...
		SunPosition,HumidityAtm,Anthropogenic,ParCalculation,...
        PropOpticalIndoors,ParHVAC,ParThermalBulidFloor,ParWindows,BEM_on,...
        TempVec_ittm2Ext,Humidity_ittm2Ext,TempVecB_ittm2Ext,Meteo_ittm,...
        RESPreCalc,fconvPreCalc,fconv,rsRoofPreCalc,rsGroundPreCalc,rsTreePreCalc,HVACSchedule)


% Nonlinear system solver
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TemperatureTot(:,1)   = Troof_imp
% TemperatureTot(:,2)   = Troof_veg
% TemperatureTot(:,3)   = Troof_interior_imp
% TemperatureTot(:,4)   = Troof_interior_veg
%--------------------------------------------------------------
% TemperatureTot(:,5)   = Temperature ground impervious area
% TemperatureTot(:,6)   = Temperature ground bare area
% TemperatureTot(:,7)   = Temperature ground vegetated area
% TemperatureTot(:,8)   = Temperature sunlit area
% TemperatureTot(:,9)   = Temperature shaded area
% TemperatureTot(:,10)  = Temperature tree canopy
% TemperatureTot(:,11)  = Interior temperature sunlit wall
% TemperatureTot(:,12)  = Interior temperature shaded wall
% TemperatureTot(:,13)  = Temperature canyon
% TemperatureTot(:,14)  = specific humidity canyon
%--------------------------------------------------------------
% TemperatureTot(:,15)  = Temperature ceiling
% TemperatureTot(:,16)  = Temperature sunlit wall
% TemperatureTot(:,17)  = Temperature shaded wall
% TemperatureTot(:,18)  = Temperature windows
% TemperatureTot(:,19)  = Temperature ground
% TemperatureTot(:,20)  = Temperature building internal mass
% TemperatureTot(:,21)  = Temperature air
% TemperatureTot(:,22)  = Humidity air
%--------------------------------------------------------------


Opt_Solv = optimoptions('lsqnonlin','Display','off','FunctionTolerance',10^-10,'MaxFunctionEvaluations',500);

lb	=	[243,243,243,243,...
        243,243,243,243,243,243,243,243,243,0,...
        243,243,243,243,243,243,243,0];

fval1 = nan(1,22); fval2 = nan(1,22); fval3 = nan(1,22); fval4 = nan(1,22);
fval5 = nan(1,22); fval6 = nan(1,22);


if BEM_on ==1
% Use temperature from previous time step as a starting point
TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(3),TempVec_ittm2Ext.TRoofVeg(3),...
                    TempVec_ittm2Ext.TRoofIntImp(3),TempVec_ittm2Ext.TRoofIntVeg(3),...
                    ...
                    TempVec_ittm2Ext.TGroundImp(3), TempVec_ittm2Ext.TGroundBare(3),TempVec_ittm2Ext.TGroundVeg(3),...
					TempVec_ittm2Ext.TWallSun(3),TempVec_ittm2Ext.TWallShade(3),TempVec_ittm2Ext.TTree(3),...
                    TempVec_ittm2Ext.TWallIntSun(3),TempVec_ittm2Ext.TWallIntShade(3),...
					TempVec_ittm2Ext.TCanyon(3),Humidity_ittm2Ext.CanyonSpecific(3),...
                    ....
                    TempVecB_ittm2Ext.Tceiling(3),TempVecB_ittm2Ext.Tinwallsun(3),TempVecB_ittm2Ext.Tinwallshd(3),...
                    TempVecB_ittm2Ext.Twindows(3),TempVecB_ittm2Ext.Tinground(3),TempVecB_ittm2Ext.Tintmass(3),...
                    TempVecB_ittm2Ext.Tbin(3),TempVecB_ittm2Ext.qbin(3)];

else
TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(3),TempVec_ittm2Ext.TRoofVeg(3),...
                    TempVec_ittm2Ext.TRoofIntImp(3),TempVec_ittm2Ext.TRoofIntVeg(3),...
                    ...
                    TempVec_ittm2Ext.TGroundImp(3), TempVec_ittm2Ext.TGroundBare(3),TempVec_ittm2Ext.TGroundVeg(3),...
					TempVec_ittm2Ext.TWallSun(3),TempVec_ittm2Ext.TWallShade(3),TempVec_ittm2Ext.TTree(3),...
                    TempVec_ittm2Ext.TWallIntSun(3),TempVec_ittm2Ext.TWallIntShade(3),...
					TempVec_ittm2Ext.TCanyon(3),Humidity_ittm2Ext.CanyonSpecific(3),...
                    ....
                    273.15,273.15,273.15,273.15,273.15,273.15,273.15,0];
end


[T1,~,fval1,exitflag1] = lsqnonlin(@targetFun,TemperatureTot,lb,[],Opt_Solv);

% If solver failed, retry with different starting value
%--------------------------------------------------------------------------
if sum(abs(fval1)>0.1)>0
    % Increasing solar radiation leads to higher temperatures
    if Meteo_ittm.SWRin(2)>Meteo_ittm.SWRin(1) && Meteo_ittm.Rain(2)<1
        r = (3*rand(22,1));
        r(13) = rand(1,1); r(21) = rand(1,1); r(14) = -10^-4; r(22) = -10^-4;
    
    % decreasing solar radiation leads to lower temperatures
    elseif Meteo_ittm.SWRin(2)<Meteo_ittm.SWRin(1)
        r = -(3*rand(22,1));
        r(13) = -rand(1,1); r(21) = -rand(1,1); r(14) = -10^-4; r(22) = -10^-4;
    else
        r = (-1 + (1+1)*rand(22,1));
        r(14) = -10^-4; r(22) = -10^-4;
    end
    
    if BEM_on ==1
    % Use temperature from previous time step as a starting point
    TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(3)+r(1),TempVec_ittm2Ext.TRoofVeg(3)+r(2),...
                        TempVec_ittm2Ext.TRoofIntImp(3)+r(3),TempVec_ittm2Ext.TRoofIntVeg(3)+r(4),...
                        ...
                        TempVec_ittm2Ext.TGroundImp(3)+r(5), TempVec_ittm2Ext.TGroundBare(3)+r(6),TempVec_ittm2Ext.TGroundVeg(3)+r(7),...
					    TempVec_ittm2Ext.TWallSun(3)+r(8),TempVec_ittm2Ext.TWallShade(3)+r(9),TempVec_ittm2Ext.TTree(3)+r(10),...
                        TempVec_ittm2Ext.TWallIntSun(3)+r(11),TempVec_ittm2Ext.TWallIntShade(3)+r(12),...
					    TempVec_ittm2Ext.TCanyon(3)+r(13),min(Humidity_ittm2Ext.CanyonSpecific(3)+r(14),0),...
                        ....
                        TempVecB_ittm2Ext.Tceiling(3)+r(15),TempVecB_ittm2Ext.Tinwallsun(3)+r(16),TempVecB_ittm2Ext.Tinwallshd(3)+r(17),...
                        TempVecB_ittm2Ext.Twindows(3)+r(18),TempVecB_ittm2Ext.Tinground(3)+r(19),TempVecB_ittm2Ext.Tintmass(3)+r(20),...
                        TempVecB_ittm2Ext.Tbin(3)+r(21),min(TempVecB_ittm2Ext.qbin(3)+r(22),0)];
    else
    TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(3)+r(1),TempVec_ittm2Ext.TRoofVeg(3)+r(2),...
                        TempVec_ittm2Ext.TRoofIntImp(3)+r(3),TempVec_ittm2Ext.TRoofIntVeg(3)+r(4),...
                        ...
                        TempVec_ittm2Ext.TGroundImp(3)+r(5), TempVec_ittm2Ext.TGroundBare(3)+r(6),TempVec_ittm2Ext.TGroundVeg(3)+r(7),...
					    TempVec_ittm2Ext.TWallSun(3)+r(8),TempVec_ittm2Ext.TWallShade(3)+r(9),TempVec_ittm2Ext.TTree(3)+r(10),...
                        TempVec_ittm2Ext.TWallIntSun(3)+r(11),TempVec_ittm2Ext.TWallIntShade(3)+r(12),...
					    TempVec_ittm2Ext.TCanyon(3)+r(13),Humidity_ittm2Ext.CanyonSpecific(3)+r(14),...
                        ....
                        273.15,273.15,273.15,273.15,273.15,273.15,273.15,0];
    end
    
    [T2,~,fval2,exitflag2] = lsqnonlin(@targetFun,TemperatureTot,lb,[],Opt_Solv);

end

% If solver failed, retry with different starting value
%--------------------------------------------------------------------------
% Retry with atmospheric forcing ------------------------------------------
if sum(abs(fval2)>0.1)>0
	TT = MeteoData.Tatm;

    if BEM_on ==1
    TemperatureTot	=	[TT,TT,TT,TT,TT, TT,TT,TT,TT,TT,TT,TT,TT,MeteoData.q_atm,...
                        TT,TT,TT,TT,TT,TT,TT,MeteoData.q_atm];
    else
    TemperatureTot	=	[TT,TT,TT,TT,TT, TT,TT,TT,TT,TT,TT,TT,TT,MeteoData.q_atm,...
                        273.15,273.15,273.15,273.15,273.15,273.15,273.15,0];
    end

    [T3,~,fval3,exitflag3] = lsqnonlin(@targetFun,TemperatureTot,lb,[],Opt_Solv);
end


% Retry with two steps extrapolated  ------------------------------------------
if sum(abs(fval3)>0.01)>0
    if BEM_on
    TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(4),TempVec_ittm2Ext.TRoofVeg(4),...
                    TempVec_ittm2Ext.TRoofIntImp(4),TempVec_ittm2Ext.TRoofIntVeg(4),...
                    ...
                    TempVec_ittm2Ext.TGroundImp(4), TempVec_ittm2Ext.TGroundBare(4),TempVec_ittm2Ext.TGroundVeg(4),...
					TempVec_ittm2Ext.TWallSun(4),TempVec_ittm2Ext.TWallShade(4),TempVec_ittm2Ext.TTree(4),...
                    TempVec_ittm2Ext.TWallIntSun(4),TempVec_ittm2Ext.TWallIntShade(4),...
					TempVec_ittm2Ext.TCanyon(4),Humidity_ittm2Ext.CanyonSpecific(4),...
                    ....
                    TempVecB_ittm2Ext.Tceiling(4),TempVecB_ittm2Ext.Tinwallsun(4),TempVecB_ittm2Ext.Tinwallshd(4),...
                    TempVecB_ittm2Ext.Twindows(4),TempVecB_ittm2Ext.Tinground(4),TempVecB_ittm2Ext.Tintmass(4),...
                    TempVecB_ittm2Ext.Tbin(4),TempVecB_ittm2Ext.qbin(4)];
    else
    TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(4),TempVec_ittm2Ext.TRoofVeg(4),...
                TempVec_ittm2Ext.TRoofIntImp(4),TempVec_ittm2Ext.TRoofIntVeg(4),...
                ...
                TempVec_ittm2Ext.TGroundImp(4), TempVec_ittm2Ext.TGroundBare(4),TempVec_ittm2Ext.TGroundVeg(4),...
				TempVec_ittm2Ext.TWallSun(4),TempVec_ittm2Ext.TWallShade(4),TempVec_ittm2Ext.TTree(4),...
                TempVec_ittm2Ext.TWallIntSun(4),TempVec_ittm2Ext.TWallIntShade(4),...
				TempVec_ittm2Ext.TCanyon(4),Humidity_ittm2Ext.CanyonSpecific(4),...
                ....
                273.15,273.15,273.15,273.15,273.15,273.15,273.15,0];
    end

    [T4,~,fval4,exitflag4] = lsqnonlin(@targetFun,TemperatureTot,lb,[],Opt_Solv);

end

% Retry with previous time step ------------------------------------------
if sum(abs(fval4)>0.1)>0
    if BEM_on
    TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(2),TempVec_ittm2Ext.TRoofVeg(2),...
                    TempVec_ittm2Ext.TRoofIntImp(2),TempVec_ittm2Ext.TRoofIntVeg(2),...
                    ...
                    TempVec_ittm2Ext.TGroundImp(2), TempVec_ittm2Ext.TGroundBare(2),TempVec_ittm2Ext.TGroundVeg(2),...
					TempVec_ittm2Ext.TWallSun(2),TempVec_ittm2Ext.TWallShade(2),TempVec_ittm2Ext.TTree(2),...
                    TempVec_ittm2Ext.TWallIntSun(2),TempVec_ittm2Ext.TWallIntShade(2),...
					TempVec_ittm2Ext.TCanyon(2),Humidity_ittm2Ext.CanyonSpecific(2),...
                    ....
                    TempVecB_ittm2Ext.Tceiling(2),TempVecB_ittm2Ext.Tinwallsun(2),TempVecB_ittm2Ext.Tinwallshd(2),...
                    TempVecB_ittm2Ext.Twindows(2),TempVecB_ittm2Ext.Tinground(2),TempVecB_ittm2Ext.Tintmass(2),...
                    TempVecB_ittm2Ext.Tbin(2),TempVecB_ittm2Ext.qbin(2)];
    else
    TemperatureTot	=	[TempVec_ittm2Ext.TRoofImp(2),TempVec_ittm2Ext.TRoofVeg(2),...
                TempVec_ittm2Ext.TRoofIntImp(2),TempVec_ittm2Ext.TRoofIntVeg(2),...
                ...
                TempVec_ittm2Ext.TGroundImp(2), TempVec_ittm2Ext.TGroundBare(2),TempVec_ittm2Ext.TGroundVeg(2),...
				TempVec_ittm2Ext.TWallSun(2),TempVec_ittm2Ext.TWallShade(2),TempVec_ittm2Ext.TTree(2),...
                TempVec_ittm2Ext.TWallIntSun(2),TempVec_ittm2Ext.TWallIntShade(2),...
				TempVec_ittm2Ext.TCanyon(2),Humidity_ittm2Ext.CanyonSpecific(2),...
                ....
                273.15,273.15,273.15,273.15,273.15,273.15,273.15,0];
    end

    [T5,~,fval5,exitflag5] = lsqnonlin(@targetFun,TemperatureTot,lb,[],Opt_Solv);

end

% Retry randomly
if sum(abs(fval5)>0.1)>0
    TT = MeteoData.Tatm;

    r = (-1 + (1+1)*rand(22,1))/10;

    if BEM_on==1
    TemperatureTot	=	[TT+r(1)*(TempVec_ittm.TRoofImp-273.15),TT+r(2)*(TempVec_ittm.TRoofVeg-273.15),...
                        TT+r(3)*(TempVec_ittm.TRoofIntImp-273.15),TT+r(4)*(TempVec_ittm.TRoofIntVeg-273.15),...
                        ...
                        TT+r(5)*(TempVec_ittm.TGroundImp-273.15), TT+r(6)*(TempVec_ittm.TGroundBare-273.15),TT+r(7)*(TempVec_ittm.TGroundVeg-273.15),...
				        TT+r(8)*(TempVec_ittm.TWallSun-273.15),TT+r(9)*(TempVec_ittm.TWallShade-273.15),TT+r(10)*(TempVec_ittm.TTree-273.15),...
                        TT+r(11)*(TempVec_ittm.TWallIntSun-273.15),TT+r(12)*(TempVec_ittm.TWallIntShade-273.15),...
				        TT+r(13)*(TempVec_ittm.TCanyon-273.15),MeteoData.q_atm,...
                        ....
                        TT+r(15)*(TempVecB_ittm.Tceiling-273.15),TT+r(16)*(TempVecB_ittm.Tinwallsun-273.15),TT+r(17)*(TempVecB_ittm.Tinwallshd-273.15),...
                        TT+r(18)*(TempVecB_ittm.Twindows-273.15),TT+r(19)*(TempVecB_ittm.Tinground-273.15),TT+r(20)*(TempVecB_ittm.Tintmass-273.15),...
                        TT+r(21)*(TempVecB_ittm.Tbin-273.15),MeteoData.q_atm];
    else
    TemperatureTot	=	[TT+r(1)*(TempVec_ittm.TRoofImp-273.15),TT+r(2)*(TempVec_ittm.TRoofVeg-273.15),...
                    TT+r(3)*(TempVec_ittm.TRoofIntImp-273.15),TT+r(4)*(TempVec_ittm.TRoofIntVeg-273.15),...
                    ...
                    TT+r(5)*(TempVec_ittm.TGroundImp-273.15), TT+r(6)*(TempVec_ittm.TGroundBare-273.15),TT+r(7)*(TempVec_ittm.TGroundVeg-273.15),...
			        TT+r(8)*(TempVec_ittm.TWallSun-273.15),TT+r(9)*(TempVec_ittm.TWallShade-273.15),TT+r(10)*(TempVec_ittm.TTree-273.15),...
                    TT+r(11)*(TempVec_ittm.TWallIntSun-273.15),TT+r(12)*(TempVec_ittm.TWallIntShade-273.15),...
			        TT+r(13)*(TempVec_ittm.TCanyon-273.15),MeteoData.q_atm,...
                    ....
                    273.15,273.15,273.15,273.15,273.15,273.15,273.15,0];
    end 
   
    [T6,~,fval6,exitflag6] = lsqnonlin(@targetFun,TemperatureTot,lb,[],Opt_Solv);
end

ResultVect = [max(abs(fval1)),max(abs(fval2)),max(abs(fval3)),max(abs(fval4)),max(abs(fval5)),max(abs(fval6))];
[~,MinSolution] = min(ResultVect);

if MinSolution == 1; T = T1; fval = fval1; exitflag = exitflag1;
elseif MinSolution == 2; T = T2; fval = fval2; exitflag = exitflag2;
elseif MinSolution == 3; T = T3; fval = fval3; exitflag = exitflag3;
elseif MinSolution == 4; T = T4; fval = fval4; exitflag = exitflag4;
elseif MinSolution == 5; T = T5; fval = fval5; exitflag = exitflag5;
elseif MinSolution == 6; T = T6; fval = fval6; exitflag = exitflag6;
end



% Create dummy function to pass further variables to the solver
function Ytot = targetFun(TemperatureTot)
	Ytot = EBSolver_UrbanClimateBuildingEnergyModel(TemperatureTot,...
        TempVec_ittm,TempVecB_ittm,Humidity_ittm,MeteoData,...
		Int_ittm,ExWater_ittm,Vwater_ittm,Owater_ittm,SoilPotW_ittm,CiCO2Leaf_ittm,TempDamp_ittm,ViewFactor,...
		Gemeotry_m,ParTree,geometry,FractionsGround,FractionsRoof,...
		WallLayers,ParSoilGround,ParInterceptionTree,...
		PropOpticalGround,PropOpticalWall,PropOpticalTree,...
		ParThermalGround,ParThermalWall,ParVegGround,ParVegTree,...
        ParSoilRoof,PropOpticalRoof,ParThermalRoof,ParVegRoof,...
		SunPosition,HumidityAtm,Anthropogenic,ParCalculation,...
        PropOpticalIndoors,ParHVAC,ParThermalBulidFloor,ParWindows,BEM_on,...
        RESPreCalc,fconvPreCalc,fconv,rsRoofPreCalc,rsGroundPreCalc,rsTreePreCalc,HVACSchedule);
end


end
